### ISSUE TITLE
Support custom file names

### ISSUE THREAD

**Issue by AlexZeitler** [PDMLab/docker-compose#1]
Instead of forcing the file name to be `docker-compose.yml`, arbitrary file names should be allowed.

**Comment by modjke** [comment]
Do you still support this project (npm repo)? If yes i'm willing to add support for custom docker-compose files and docker-compose exec, can be profitable for my project too

**Comment by AlexZeitler** [comment]
Yes, it is actively maintaned and used.

Looking forward to your PRs 👍🏻

**Comment by AlexZeitler** [comment]
Thanks for your PRs!  Version `0.6.0` has been published on [npm](https://npmjs.com/package/docker-compose).
