### ISSUE TITLE
BUG - output "err" is actually not an error

### ISSUE THREAD

**Issue by shaypeleg1** [PDMLab/docker-compose#101]
when using, "buildOne"/"run" (maybe more commands), the output response from the promise returns `{ exitCode: NUMBER, "err": "string", "out": "string }.`

the "err" that gets printed is not actually an error when exiting on code.

example:
``` 
{ exitCode: 0,
  err: 'Building docker-example\n',
  out:
  'Step 1/13 : bal bal bla ....' }
```

``` 
{ 
 exitCode: 0,
  err: 'Creating network "docker-example" with the default driver\n',
  out: 'docker-example-test\n' }

```

**Comment by Steveb-p** [comment]
As you can see below it's not really a bug - at least not in this library. We're simply reading the `stderr` error ouput stream and pass it into `err` property.

https://github.com/PDMLab/docker-compose/blob/5c7443001155f8b551f2690c7af21c65ebeb0cb6/src/index.ts#L92-L94
