### ISSUE TITLE
Enhancement: allow --abort-on-container-exit command option for up methods

### ISSUE THREAD

**Issue by lancerutkin** [PDMLab/docker-compose#105]
Currently if I run an up method with the following command option:

`commandOptions: ['--abort-on-container-exit']`

I'll receive the following error message:

`{ exitCode: 1,
  err:
   '-d cannot be combined with --abort-on-container-exit or --attach-dependencies.\n',
  out: '' }`

This is because upAll, upMany, and upAll all always pass the `-d` flag. 

To make `--abort-on-container-exit` usable we have it replace `-d` when the user passes `--abort-on-container-exit` as a commandOption.

Happy to open up a PR for this.

**Comment by AlexZeitler** [comment]
Makes sense to me - go for it 🚀

**Comment by Steveb-p** [comment]
Shouldn't this be closed?

**Comment by AlexZeitler** [comment]
Yep
