### ISSUE TITLE
Can I just pass in a yaml string instead of yaml file names?

### ISSUE THREAD

**Issue by nielinjie** [PDMLab/docker-compose#109]
Can I just pass in a yaml string instead of yaml file name(s)? Because my config yaml is dynamic generated and no need to be saved.

**Comment by Steveb-p** [comment]
@nielinjie this repository practically wraps calls to `docker-compose` binary, and it doesn't support as far as I can tell receiving it's configuration from standard input.

This practically means no, and I doubt it will be supported - it would mean building functionality that does not exist in `docker-compose` itself.

**Comment by AlexZeitler** [comment]
I wonder if this would be possible to implement. @nielinjie would you be willing to send a pull request?

**Comment by emileae** [comment]
I'd be very interested in this enhancement, any tips on where to start?

**Comment by AlexZeitler** [comment]
@nielinjie @emileae Did you notice we got this thanks to @furstenheim by #124 a while ago?

**Comment by emileae** [comment]
Really cool, thanks for letting me know!
