### ISSUE TITLE
rm for single container

### ISSUE THREAD

**Issue by MOTORIST** [PDMLab/docker-compose#111]
Hi!
Usage rm:
rm [options] [SERVICE...]

Why not?
```
export const rm = function (options?: IDockerComposeOptions, container?: string): Promise<IDockerComposeResult>;
```

**Comment by AlexZeitler** [comment]
@MOTORIST 👋 

Did you try putting the service name at the last entry of `options.commandOptions`?
If this doesn't do the trick:

Would you mind sending a PR including a test?

`container` should be `service`

```
export const rm = function (options?: IDockerComposeOptions, container?: string): Promise<IDockerComposeResult>;
```

Maybe it might make sense to allow 1..n `service`s to be `rm`ed.

@Steveb-p Thoughts/Comments?

**Comment by Steveb-p** [comment]
Sure, why not.

```ts
export const rm = function (options?: IDockerComposeOptions, ...services: string[]): Promise<IDockerComposeResult>;
```

or

```ts
export const rm = function (options?: IDockerComposeOptions, services: string | string[]): Promise<IDockerComposeResult>;
```

or

```ts
export const rm = function (options?: IDockerComposeOptions, services: string[]): Promise<IDockerComposeResult>;
```

depending on your preference.

Destructuring seems more `docker-compose`-like. Allows passing a single-string service or multiple without requiring internal type checks in function. All we will need to check is if `services.length` > 0.

**Comment by MOTORIST** [comment]
> Did you try putting the service name at the last entry of options.commandOptions

No, this not expected behavior

Maybe?

```
export const rmOne = function (service: string, options?: IDockerComposeOptions): Promise<IDockerComposeResult>
```

**Comment by AlexZeitler** [comment]
I would prefer the destructuring approach.

**Comment by Steveb-p** [comment]
There were not tests against `rm` function actually. Also, `commandOptions` have to have `"-s"`, otherwise running containers will not be stopped.

**Comment by AlexZeitler** [comment]
@Steveb-p thanks for your PR. 📦 docker-compose@0.23.4 is released on npm.
