### ISSUE TITLE
Add way to see started containers and finer grained logging

### ISSUE THREAD

**Issue by cristianrgreco** [PDMLab/docker-compose#120]
Hi, thanks for providing this great library! I'm incorporating it into https://github.com/testcontainers/testcontainers-node and it works great, I just have a couple of questions:

1. Is there a way to get only the containers started by a given docker-compose - perhaps an array of container IDs? 
2. Is there a way to see if docker-compose up will pull an image? I'd like to provide some more logging around this so users see what's causing a delay. I know docker-compose can expose all the logs but I'd like more fine grained control instead of logging everything

**Comment by AlexZeitler** [comment]
@cristianrgreco Hi! Happy to see docker-compose is actively being used. I’m afraid, apart from parsing the output there’s no structured data available from docker-compose(the CLI itself)

**Comment by cristianrgreco** [comment]
Sure no worries, thanks for the response. 

For anyone else for the first point, I found that I can set `COMPOSE_PROJECT_NAME` as an env variable which will set a label for all the resources which you can filter on later:

```typescript
await dockerCompose.upAll({
  env: {
    ...process.env,
    COMPOSE_PROJECT_NAME: `my-project-name`,
  }
});
```

Running `docker inspect` on one of the containers shows the following label:

```
"com.docker.compose.project": "my-project-name"
```

So you could get all running containers and filter by the label specified.
