### ISSUE TITLE
Support applying labels to created containers/networks/volumes/images

### ISSUE THREAD

**Issue by cristianrgreco** [PDMLab/docker-compose#121]
Hi, as part of integrating this library with testcontainers-node, it'd be great if we could provide a map of labels when we up different resources. The use case for this is we tag the created resources with labels so we can clean everything up after. I can't find support for providing labels via either `composeOptions` or `commandOptions`

**Comment by Steveb-p** [comment]
@cristianrgreco `docker-compose` binary allows "overwriting" of labels in `run` command. You should be able to pass it into `commandOptions`.

See: https://docs.docker.com/compose/reference/run/

This library is a wrapper around `docker-compose` binary so whatever the binary can or cannot do applies here usually.

**Comment by cristianrgreco** [comment]
Hi @Steveb-p, thanks for the quick response. I think that'd work if I use `run` but I'm running `upAll`. I just tried running `upAll` with `["-l", "key=value"]` as both `commandOptions` and `composeOptions` and it's not coming through.

**Comment by Steveb-p** [comment]
> Is this library able to return me a list of containers that can be run?

@cristianrgreco You can use `config` operations for that.

https://github.com/PDMLab/docker-compose/blob/664b8d4eb69ddaf088147aaa73fdfd4a121612c3/src/index.ts#L201-L211

**Comment by cristianrgreco** [comment]
I was able to achieve what I wanted by setting `COMPOSE_PROJECT_NAME` in the `env` in `IDockerComposeOptions`.
