### ISSUE TITLE
Export the `execCompose` function

### ISSUE THREAD

**Issue by eugene-manuilov** [PDMLab/docker-compose#162]
Can you update the index.js file to export the `execCompose` function as well?

**Comment by AlexZeitler** [comment]
@eugene-manuilov Just out of curiosity: what's your use case?

**Comment by AlexZeitler** [comment]
@eugene-manuilov 📦 0.23.11 is available on npm including exported `execCompose`.

**Comment by Steveb-p** [comment]
> @eugene-manuilov Just out of curiosity: what's your use case?

I'm actually wondering the same :smile: Not like it's an issue to expose that one though.
