### ISSUE TITLE
Issues with Compose V2

### ISSUE THREAD

**Issue by colececil** [PDMLab/docker-compose#177]
Docker Desktop opted me in to the Compose V2 beta without me realizing it, and I ran into some issues with it using this library in an Electron app my team built. Here are the issues I saw (I also mentioned them in [a comment in Docker's GitHub issue](https://github.com/docker/for-mac/issues/5800#issuecomment-893887340)):

- The Docker Compose logs being output in our Electron app no longer had color.
- When using the `buildMany` function, Docker Compose not only built the services I passed in, but also the services they depend on (with Compose V1, only the services I pass in are built).
- I was getting some really long Go error message sometimes when running containers. I couldn't figure out what the message meant (and I don't remember exactly what it said), but things seemed to still be working even after getting the error message.

I'm not sure if these issues are under your control or not, but thought I'd at least let you know about them.

**Comment by AlexZeitler** [comment]
@colececil Thanks for reporting! We’re currently testing against v2 but we’re not there yet.

**Comment by strophy** [comment]
We have forked this to add Compose v2 support, what do you think of [this implementation](https://github.com/dashevo/docker-compose) @AlexZeitler? Interested in a PR or what are your plans going forward to add support?

**Comment by AlexZeitler** [comment]
@strophy If you would send a PR I'll be more than happy to merge it. 

For v1 compatibility, I would suggest not changing the default implementation but maybe export a `composev2` which runs your implementation. As v2 has diverged from v1 already I guess this should be the easiest way to maintain both side by side.

**Comment by colececil** [comment]
@strophy, thanks for working on this! Has there been any progress in merging the changes back here? Or do I need to use `@dashevo/docker-compose` instead from here out?

**Comment by strophy** [comment]
Hi @colececil the work to prepare `@dashevo/docker-compose` was done by a contractor, I've asked him to look at how much work a PR would be

**Comment by wasserholz** [comment]
Docker compose v2 support is quite important. What would be the next steps to get this pull request going?

**Comment by AlexZeitler** [comment]
@strophy I just noticed I can create a pull request from your repo to this repo. 

This would allow us to move on without work required from your side.

Are you ok with this?

**Comment by strophy** [comment]
@AlexZeitler by all means please go ahead, we kept your MIT License on the fork! We've just been overloaded and didn't get around to doing a PR :sweat_smile: 

It has been working well for a long time in production now so should be an easy merge. Thanks for continuing to maintain the project!

**Comment by AlexZeitler** [comment]
@strophy Thanks!

Progress can be tracked here: https://github.com/PDMLab/docker-compose/pull/224

**Comment by AlexZeitler** [comment]
`docker-compose` (v1) and `docker compose` (v2) have diverged already causing about 10 failing tests now. 

For example `docker compose config` doesn't return the `version` info from the `docker-compose.yml` file in recent versions.

Hence, I've decided to create to separate implementations of `docker-compose` for v2 (but it'll be part of this library).

This resulted in a new PR #228.

#224 will be closed.
