### ISSUE TITLE
Error running docker-compose

### ISSUE THREAD

**Issue by astrutzenberger** [PDMLab/docker-compose#210]
We are currently using Docker version 20.10.17 and Docker Compose version v2.4.1 and get this error:
```
Error: spawn docker-compose ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn docker-compose',
  path: 'docker-compose',
  spawnargs: [
    '-f',
    '/home/astrutzenberger/wp-env/58985d03f377084efeb844eaaf1d037e/docker-compose.yml',
    'up',
    '-d',
    'mysql'
  ]
}
```
The cause seems to be, that the command for docker compose has changed from 'docker-compose' to 'docker compose' in the new version. Are there any plans to update this?

**Comment by AlexZeitler** [comment]
Thanks for reporting the issue.

There has been #164 and some discussions: https://github.com/PDMLab/docker-compose/discussions/151

Looking at our monthly download numbers on npm, looks like there are still a lot of people using `docker-compose 1.x` so it won't be an option to just change the executable from `docker-compose` to `docker compose`.

We need some sort of flag to indicate which major version (1/2) should be used.

Would you be willing to send a PR for this?

For me it would be to get out a new version supporting both versions fast at the cost of compatibility issues with v2 being fixed as they arise (some should very fast when running the existing tests against v2).

@Steveb-p Thoughts?

**Comment by Steveb-p** [comment]
Cannot disagree with what's already said :smile: 

`docker compose` has a json format already included in itself afaik, so there will be some changes to be done. 

Design-wise I'd propose extracting an interface from the existing implementation and write a v2 compatible version? And then we would provide a way of selecting which implementation to use by exporting a "factory" method? How does that sound?

I think that's a better approach because it will clearly separate both.

**Comment by vaideek** [comment]
Docker official documentation itself suggest that if docker engine version is 19.03.0+ then docker compose version should be 3.8 which is latest .
Docker-compose was used for older versions now it is replaced with docker compose.

**Comment by Steveb-p** [comment]
> 

This doesn't really change much. We need to maintain support for both - at least for the near future. And this library doesn't try to read the configuration files or interact with docker engine, so this information is unaccessible.

We can do and add some sort of detection, but at this point we're missing an implementation itself.

**Comment by astrutzenberger** [comment]
Hi there! Thanks for the replies. I have actually found a quick workaround, which works great and solves my problem for now: https://stackoverflow.com/questions/72099653/how-to-alias-docker-compose-to-docker-compose
