### ISSUE TITLE
integration of list commands

### ISSUE THREAD

**Issue by alex-Symbroson** [PDMLab/docker-compose#267]
Are there plans on integrating list commands such as `image list`, `container list` and so forth?

I need `image list` for another project to detect which images are already available and can be `up`'ed immediately without rebuilding

**Comment by AlexZeitler** [comment]
Containers can be listed using the [`ps`](https://github.com/PDMLab/docker-compose/blob/master/src/v2.ts#L496) command.

`images` is not supported right now, but we're taking PRs.

**Comment by alex-Symbroson** [comment]
should be working, tests are based off `ps`
