### ISSUE TITLE
allow configuration setting for interactive mode

### ISSUE THREAD

**Issue by stguitar** [PDMLab/docker-compose#27]
I have a use case where I plan to use this package to startup a collection of services for development, based on what I am working on.  It would be nice to not send '-d' to the command.  

I could see this being an option on the options object:

`option.interactive: true`

where the '-d' being passed on each command would be skipped. 

Would this be a valid change?

**Comment by AlexZeitler** [comment]
Sure, go ahead :+1: . Looking fwd to your PR :bowing_man:

**Comment by stguitar** [comment]
@AlexZeitler OK, So I have decided to back off of this due to a few reasons.  This is challenging because you really do not know when a given container has launched while interactive mode.  detached mode is easy to know when the docker-compose command has "finished" because it basically gives immediate feedback (the container ID) and then the command is done.  

For what I need, a better fit turned out to be using a different node package - concurrently - which did exactly what I was looking for.

I still think if you are firing up a container to test against, this package makes a lot of sense.  I was just wanting to use it more like a runner for a collection of service containers.
