### ISSUE TITLE
docker-compose v1 is deprecated

### ISSUE THREAD

**Issue by tpluscode** [PDMLab/docker-compose#281]
I see issues and PRs #276 #277 #278 but I question whether that effor is really necessary in the first place

`docker-compose` (v1) has been deprecated since June 2023 https://docs.docker.com/compose/migrate/

Recently, GitHub workflow runners do not come with `docker-compose` any more, resulting in error `Error: spawn docker-compose ENOENT`

I think that rather than trying to patch an already complex build setup, v1 should be dropped a v2 should be the only export from this package...

**Comment by Steveb-p** [comment]
A this point in time, yeah. Guess we could release a major version just to be strict about it.

**Comment by AlexZeitler** [comment]
Makes sense

**Comment by AlexZeitler** [comment]
Since I don't have much time in the next few weeks (and honestly haven't done anything with Node.js for over a year - except maintaining this library), I tagged it with up for grabs.

**Comment by tpluscode** [comment]
Happy to send a PR
