### ISSUE TITLE
Additional API proposal

### ISSUE THREAD

**Issue by modjke** [PDMLab/docker-compose#3]
So while i was implementing an npm build system for my docker-compose project i had this idea of changing existing API for this module (or adding it on top of an existing one) to make this module more OOPeish and to avoid repetion of `cwd` , `log` and other parameters.
Would you be interested in something like this?
```javascript
const DockerCompose = require('docker-compose')
// DockerCompose.method will still be a thing (legacy support), but the main course is
const compose = new DockerCompose({
  cwd: '.',
  log: false,
  config: 'docker-compose.yml'
})

await compose.build()
await compose.up()
const container = 'node'
const command = 'npm install'
await compose.exec(container, command, {
  log: true, // will override initial constructor settings
  workdir: './var/www' //  cli args for exec and other commands will be also supported
})
```

**Comment by AlexZeitler** [comment]
That's indeed something we've been thinking about. So feel free to add it. Again, looking forward to it.

**Comment by modjke** [comment]
That's gonna take some time, don't give up on me :)

**Comment by AlexZeitler** [comment]
Take your time! 😉

**Comment by SgtPooki** [comment]
maybe i'm missing something but how exactly is this proposal different than what exists? Can you call out the changes and additions so others could see the pros/cons of your proposal?

**Comment by modjke** [comment]
> maybe i'm missing something but how exactly is this proposal different than what exists? Can you call out the changes and additions so others could see the pros/cons of your proposal?

Well, it was created long time ago and API has changed since, no reason to keep this open anylonger
