### ISSUE TITLE
run has bad argument order and does not allow usage of composeOptions

### ISSUE THREAD

**Issue by maximelebastard** [PDMLab/docker-compose#42]
Here is an example of a script where I want to run a yarn install from a specific workdir on my container
```
docker-compose run --workdir="/app/backend" node yarn install
```

The equivalent would be 
```
await dockerCompose.run('node', 'yarn install', {
        composeOptions: [['--workdir','/app/backend']]
	});
```

But this call will generate a call with bad argument order, passing the workdir to the command inside the container and not to the container itself

```
docker-compose run node yarn install --workdir="/app/backend"
```

Is there a workaround I don't get or is it a bug ?

**Comment by AlexZeitler** [comment]
It is likely to be a bug. Can you please also share a Dockerfile and docker-compose.yml for easier repro?

**Comment by maximelebastard** [comment]
Here is a full demo !
https://github.com/maximelebastard/pdmlab-docker-compose-issue42

Just clone, `yarn install` and `node index.js` 😉 

Thanks for the quick answer anyway, happy to help if needed

**Comment by AlexZeitler** [comment]
Thanks, will look into it this evening.

**Comment by AlexZeitler** [comment]
@maximelebastard it should now work as expected using this code - as you can see `composeOptions` have changed to be `commandOptions` now:

```js
compose.run('some-service', 'cat hello.txt', {
      cwd: path.join(__dirname),
      log: true,
      config: 'docker-compose-42.yml',
      commandOptions: [ '--workdir', '/mountedvolume/nested/dir' ]
    });
```

We now also have `composeOptions` which are the global `docker-compose` CLI options:

```js
compose.run('some-service', 'cat hello.txt', {
      cwd: path.join(__dirname),
      log: true,
      config: 'docker-compose-42.yml',
      composeOptions: [ '--verbose' ],
      commandOptions: [ '--workdir', '/mountedvolume/nested/dir' ]
    });
```

The fixed version `0.14.2` is available on npm.

**Comment by maximelebastard** [comment]
This is great ! I'll test it tomorrow.
Thanks a lot for the fix !

**Comment by maximelebastard** [comment]
It works perfectly - thank you for your efficiency

**Comment by AlexZeitler** [comment]
Great to hear. If you have other issues or suggestions, just let us know.
