### ISSUE TITLE
Introduce changelog.md

### ISSUE THREAD

**Issue by AlexZeitler** [PDMLab/docker-compose#50]
`mocha` has a nice one:
https://github.com/mochajs/mocha/blob/master/CHANGELOG.md

**Comment by AlexZeitler** [comment]
[Our Changelog](https://github.com/PDMLab/docker-compose/blob/master/CHANGELOG.md)

**Comment by Steveb-p** [comment]
@AlexZeitler you've got this automated or are you writing this by hand?

**Comment by AlexZeitler** [comment]
It's done by hand currently but I'm open for better solutions of course.

**Comment by Steveb-p** [comment]
@AlexZeitler Personally I'm using `standard-version` for my own changelogs, but had no luck adjusting styling (at the moment when I introduced them, and I haven't really taken too much time trying).

https://github.com/conventional-changelog/standard-version
