### ISSUE TITLE
Allow config calls

### ISSUE THREAD

**Issue by Steveb-p** [PDMLab/docker-compose#53]
`docker-compose` allows us to call `docker-compose config` and receive configuration yaml as a result (for it's "main" functionality). This is different than just merging yaml files since all environment variables are replaced accordingly as docker-compose does (also taking into account possible `.env` files I believe).

This command also allows for viewing service lists when called with `--services` options, volumes with `--volumes` option and container hashes (as I understand it) with `--hash="*"` option (filtered as well).

From my point of view, `config` call would allow one to see what services are available, even if they have not yet been created (since those would not show up in `docker-compose ps`).

I'll gladly provide a PR for it, since I'll be probably using this functionality in my own application.

**Comment by AlexZeitler** [comment]
@Steveb-p Great suggestion - looking forward to your PR!

**Comment by Steveb-p** [comment]
@AlexZeitler I've looked at the current API, and it does not correspond 1:1 to docker-compose commands. Do you have any particular preference towards naming?

I feel they should be split to 3 different commands?

**Comment by AlexZeitler** [comment]
What would you suggest (wrt naming/splitting)?

**Comment by Steveb-p** [comment]
> What would you suggest (wrt naming/splitting)?

I've went with `config`, `configServices` & `configVolumes`, to roughly keep them "under the same namespace" and designated that they are related to configuration, not actually running containers.

Some code style (eslint) changes went along with the PR, hope you don't mind? I've got them configured automatically according to your project settings, and I didn't notice them until after PR was created ;)

Feel free to request any changes you like, obviously ;)

**Comment by AlexZeitler** [comment]
Thanks, will look into it tomorrow morning in detail.
I think the TypeScript typings need to be updated as well.

**Comment by Steveb-p** [comment]
> I think the TypeScript typings need to be updated as well.

Forgot about it, fixed.

**Comment by AlexZeitler** [comment]
@Steveb-p I checked out your PR and I'm trying to understand (mostly because I haven't used `config` until now) the exact intention behind splitting `config` into three commands.

I tried this which also works to output just the services without volumes:

```
const std = await compose.config({ cwd: path.join(__dirname), log: true, config: 'docker-compose-42.yml', commandOptions: ['--services'] });
```

**Comment by Steveb-p** [comment]
> @Steveb-p I checked out your PR and I'm trying to understand (mostly because I haven't used `config` until now) the exact intention behind splitting `config` into three commands.

I was trying to follow `upAll`, `upMany`, `upOne`, `buildAll`, etc. That's my reasoning. From my point of view since there already existed "helper" functions, then creating three different functions for practically different "queries" would simplify their use for little extra cost of maintaining them.

Should I merge them together and only add some information to docs regarding their additional, potential use?

**Comment by AlexZeitler** [comment]
Ok, then splitting makes perfectly sense.
