### ISSUE TITLE
Use same docker image versions for tests

### ISSUE THREAD

**Issue by Steveb-p** [PDMLab/docker-compose#61]
I'm sitting here with a very, very bad internet connection and without docker images preloaded on my laptop (I'm using a different one that usually) and I've noticed that there are two different versions of MongoDB service being pulled - one `3.4` and second `3.4.0`. The same goes for alpine, but considering it's a lot smaller...

Anyway, I think we should use the same images in all tests?

EDIT: Also preferably we could use smaller "service" image instead of Mongo? Like nginx:alpine? (150 MB~ish worth of docker layers would become around 7 MB?)

**Comment by AlexZeitler** [comment]
As can be seen in #45 3.4 broke the test.
Using nginx:alpine would be fine but we need to make the start blocking then.

**Comment by Steveb-p** [comment]
I'd say we should pin to a specific version anyway to prevent such random test failures :)

Assertion in the test in question can also be "rephrased" to check for something else than OS name :) It is a test of `docker-compose exec` anyway :)

**Comment by AlexZeitler** [comment]
👍

**Comment by AlexZeitler** [comment]
The entry for `nginx:alpine` in `docker-compose` should contain this to be blocking: 

`command: nginx -g "daemon off"`

**Comment by Steveb-p** [comment]
@AlexZeitler I'll provide PR in the evening. Had a few days off due to holidays & being busy at work.

**Comment by AlexZeitler** [comment]
👍 Take your time

**Comment by Steveb-p** [comment]
Intentionally left Nginx with Debian as OS for your `checkOS` tests.

Also, is there any particular reason for `tape` as test framework? I'm not really familiar with it, but it doesn't seem to be "vocal" about which tests exactly did not pass and it's kinda a hurdle to look through output to see :) Not to mention not really being able to filter tests to only run those I'm interested in (I didn't really look too much into it, just curious).
