### ISSUE TITLE
Exposing other child_process.exec options

### ISSUE THREAD

**Issue by zaucy** [PDMLab/docker-compose#7]
I would like to set other [child_process.exec options](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) on the docker compose calls. Specifically the `env` object so I may set my docker-machine environment variables.

**Comment by AlexZeitler** [comment]
@zaucy This can be closed, right?

**Comment by zaucy** [comment]
Yes. Although someone might see this issue as all other child_process.exec options.

**Comment by stguitar** [comment]
How is this used?  My use case is that each dev may have their config param and instead of changing the docker-compose file in the project, id like to inject environment variables from the host (or reading a local config file or something) to be included in the images spun up

**Comment by stguitar** [comment]
So I was able to work around this by following the suggestions here:

[https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js](https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js)

Which led me to doing this...  Not sure if this is expected, but without the process.env.PATH being there, I was unable to start up a compose file while passing in custom environment variables via js.

```
let env = {PATH: process.env.PATH};
env.foo = 'bar';

compose.upAll({ cwd: path.join(__dirname), log: true, env: env})
```

**Comment by mikicho** [comment]
I agree. this is cumbersome to set the `PATH` specifically:
```
await dockerCompose.upAll({
    cwd: path.join(__dirname),
    log: true,
    env: {PATH: process.env.PATH, PG_PORT: 5432} ,
});
```
