### ISSUE TITLE
export interfaces again

### ISSUE THREAD

**Issue by LarsKumbier** [PDMLab/docker-compose#85]
The typescript interfaces of options are not exported anymore, making it impossible to allow type-checking in compositions:

```typescript
/// /dist/index.d.ts
interface IDockerComposeOptions {
    cwd?: string;
    config?: string | string[];
    log?: boolean;
    composeOptions?: string[] | (string | string[])[];
    commandOptions?: string[] | (string | string[])[];
    env?: NodeJS.ProcessEnv;
}
[...]
```

**Comment by Steveb-p** [comment]
uhmmm... whoops? I'll fix it right away.

**Comment by Steveb-p** [comment]
PR is ready, @AlexZeitler will merge it as soon as he can probably.

Sorry I simply forgot to export those interfaces when codebase was migrated to typescript.

**Comment by LarsKumbier** [comment]
Faster than me. :)
