### ISSUE TITLE
Documentation and function signatures use of the word 'container' 

### ISSUE THREAD

**Issue by zaucy** [PDMLab/docker-compose#9]
See the following function signatures:

```JavaScript
exec(container, command, options)
run(container, command, options)
```

Both use `container` for their first argument name. In the docker compose documentation/help command these are refered to as `service`. It would be benefical if argument name choice as well as the README documentation was consistent with the docker-compose documentation.

This might be nit picky, but when I first came across this npm module I wasn't sure if the `container` argument actually meant the container's name/id generated by docker-compose. I expected it to be the service name (which it is), but from the README and the function argument it self I had to check.

**Comment by AlexZeitler** [comment]
This makes sense.
