### ISSUE TITLE
Enhancement: typed output of commands

### ISSUE THREAD

**Issue by LarsKumbier** [PDMLab/docker-compose#95]
The current implementation exposes very low-level information on the result of a command with the interface

```
export interface IDockerComposeResult {
  exitCode: number | null;
  out: string;
  err: string;
}
```

This has the disadvantage of leaving the interpretation of the output to the user, leading in a lot of boilerplate code that all users of docker-compose have to write. Instead it would be better to provide more introspective into the result by typing it:

```
export interface IDockerComposeResult<T> {
  exitCode: number | null;
  out: string;
  err: string;
  result: T | null;
}
```

This should be given for every mapped subcommand of docker-compose. An example for the `port` subcommand:

```
interface IDockerComposePortResult {
  address: string;
  port: number;
}
```

If an error occurs, the result should be null, since the error output will already be present in the `err` key.

We should use github's project to track, which subcommands have already been enhanced.

_Originally posted by @stefanmeschke in https://github.com/PDMLab/docker-compose/pull/52#issuecomment-533993954_

**Comment by AlexZeitler** [comment]
@LarsKumbier 

> We should use github's project to track, which subcommands have already been enhanced.

Would you use notes for each subcommand or use this issue and add a todo list to it?
