### ISSUE TITLE
How to remove Volumes on compose.down() ?

### ISSUE THREAD

**Issue by OlmoDalco** [PDMLab/docker-compose#96]
I need compose not only to remove containers but also volumes defined in the compose file. 
So far i am not sure, how to properly pass  -v, --volumes to compose.down()

**Comment by Steveb-p** [comment]
You should be able to achieve that by calling

```typescript
down({
  commandOptions: ['--volumes'],
})
```
or
```typescript
down({
  commandOptions: '--volumes',
})
```

See: 
https://github.com/PDMLab/docker-compose/blob/1585dbb62a6a656d1e60079524f2b833a93a3a8f/src/index.ts#L3-L10
and:
https://github.com/PDMLab/docker-compose/blob/1585dbb62a6a656d1e60079524f2b833a93a3a8f/src/index.ts#L123-L125
