### ISSUE TITLE
Use standard-version / conventional commit messages

### ISSUE THREAD

**Issue by AlexZeitler** [PDMLab/docker-compose#98]
As added to [express-http-problem-details](https://github.com/PDMLab/express-http-problem-details) [recently](https://github.com/PDMLab/express-http-problem-details/pull/9/commits/91ba676c0bd9e151e8e2f8dc63c6c468e4d0b5e5)

@Steveb-p  thoughts?

**Comment by Steveb-p** [comment]
Sure, I'm already using `standard-version` for some of my other projects (without enforcing those rules though), so I'm :+1:
